### PR TITLE
Go implementation

### PR DESCRIPTION
**Pull request by ilyakaznacheev**
Petooh interpreter written in pure Go.
Test coverage > 90%

### CODE REVIEW

**Comment by Ky6uk** [comment]
@ilyakaznacheev Thanks so much! I am sure everybody wait that implementation in 2018. Did you finish that?

**Comment by ilyakaznacheev** [comment]
In 2K18 every big project has to have some Go support :)
It was tricky to create a PR during [Github technical problems](https://blog.github.com/2018-10-21-october21-incident-report/), but I finally made it.

**Comment by ilyakaznacheev** [comment]
Oops closed by mistake...

**Comment by ilyakaznacheev** [comment]
So now it's finally done.

**Comment by Ky6uk** [comment]
Cool! I did merge it through CLI cause of github's web interface problem.

**Pull request closed without merging**
